In [1]:
print("布爾型")
print("浮點型")
print("整型")

布爾型
浮點型
整型


In [2]:
s=['y','o','y','o']
s[:]

['y', 'o', 'y', 'o']

In [3]:
import numpy as np
import pandas as pd
import warnings
import talib as ta
import pandas as pd
warnings.filterwarnings('ignore')

from datetime import datetime

symbol=['600029.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data['close']
data = pd.DataFrame(data_dict)

print(data.iloc[:])

                     600029.XSHG
datetime                        
2017-01-03 15:00:00        11.64
2017-01-04 15:00:00        11.72
2017-01-05 15:00:00        11.80
2017-01-06 15:00:00        11.80
2017-01-09 15:00:00        11.85
2017-01-10 15:00:00        12.73
2017-01-11 15:00:00        12.13
2017-01-12 15:00:00        11.98
2017-01-13 15:00:00        11.97
2017-01-16 15:00:00        12.02
2017-01-17 15:00:00        11.97
2017-01-18 15:00:00        12.03
2017-01-19 15:00:00        11.98
2017-01-20 15:00:00        12.03
2017-01-23 15:00:00        12.17
2017-01-24 15:00:00        12.18
2017-01-25 15:00:00        12.22
2017-01-26 15:00:00        12.08
2017-02-03 15:00:00        12.03
2017-02-06 15:00:00        11.89
2017-02-07 15:00:00        11.89
2017-02-08 15:00:00        11.95
2017-02-09 15:00:00        11.98
2017-02-10 15:00:00        12.15
2017-02-13 15:00:00        12.20
2017-02-14 15:00:00        12.18
2017-02-15 15:00:00        12.30
2017-02-16 15:00:00        12.48
2017-02-17

In [4]:
data=pd.read_excel('sz50.xlsx',sheetname=None,index_col='datetime')

MA = ta.MA(data['600029.XSHG'].close.values,10)
print(type(MA))
print(MA[-5:]
      

SyntaxError: unexpected EOF while parsing (<ipython-input-4-ca695e2ea0d0>, line 6)

In [5]:
import warnings
warnings.filterwarnings('ignore')
from datetime import datetime
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data.loc[:]
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


In [6]:
import numpy as np
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data = pd.read_excel('sz50.xlsx', symbol, index_col='datetime')
print(data.iloc[-20:])

AttributeError: 'collections.OrderedDict' object has no attribute 'iloc'

In [7]:
arr1 = np.arange(25).reshape(5,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
